// <auto-generated />
namespace GeneralStore.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class secondcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "202012100444446_second-commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
